### ISSUE TITLE
Ambiguity

### ISSUE THREAD

**Issue by bernaferrari** [khronokernel/Getting-Started-With-ACPI#2]
In SSDT the easy way, it is written:

> This must be done on the target machine running either Windows or Linux

Can I make this under macOS? (I have Clover already working). It is unclear.. Because a) Clover might affect the results or b) you are just accounting that the person is installing macOS for the first time.

**Comment by khronokernel** [comment]
Hello,
So regarding the question, no you cannot run SSDTTime from macOS. Or to be more specific, you cannot dump your DSDT from macOS. As mentioned in [SSDT: the long way](https://github.com/khronokernel/Getting-Started-With-ACPI/blob/master/ssdt-long.md),  it must be dumped outside of macOS as ACPI patches will have already been applied. This is an issue when dealing with EC and IRQ patches, you can however use a clean DSDT with SSDTTime to make the SSDTs so long as the DSDT is unaltered

**Comment by bernaferrari** [comment]
That was stupid. Thanks 🤦‍♂️😂
