### ISSUE TITLE
[BUG] Broken link

### ISSUE THREAD

**Issue by dreamwhite** [khronokernel/Getting-Started-With-ACPI#7]
Link: https://github.com/dortania/Getting-Started-With-ACPI/blob/master/Universal/xosi.md
Broken link: https://github.com/khronokernel/Getting-Started-With-ACPI/blob/master/extra-files/SSDT-XOSI.aml

Please provide .dsl files as you already explained how to compile a SSDT using iasl :)

**Comment by khronokernel** [comment]
Oh I don't plan to keep XOSI around in the guide, it shouldn't be mentioned anywhere other than the front page which I meant to remove mentions of. It's a hacky SSDT and the GPI0 guide is a much better solution, the md file is just there as I haven't cleaned it up yet

**Comment by khronokernel** [comment]
Oh just realized this is the old repo, think you meant to go to the new one
